### PR TITLE
Bug Fix

### PR DESCRIPTION
**Pull request by enzok**
Loading json files from local disk in _read_from_disk() should return dict from load.json()

### CODE REVIEW

**Comment by doomedraven** [comment]
having the same issue
```
mitre.enterprise.techniques
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cape/.local/lib/python3.8/site-packages/pyattck/attck.py", line 253, in enterprise
    from .enterprise import EnterpriseAttck
  File "/home/cape/.local/lib/python3.8/site-packages/pyattck/enterprise.py", line 7, in <module>
    class EnterpriseAttck(Base):
  File "/home/cape/.local/lib/python3.8/site-packages/pyattck/enterprise.py", line 41, in EnterpriseAttck
    __nist_controls_json = NistControls(**Base.config.get_data("nist_controls_json"))
TypeError: type object argument after ** must be a mapping, not NoneType
```

tested this fix, it fixes bug for me

**Comment by doomedraven** [comment]
do you have plans to release 7.1.0? or any version in pypi with fixes?

**Comment by MSAdministrator** [comment]
@doomedraven yeah I can do that tomorrow. Must have missed the release but will resolve.

**Comment by doomedraven** [comment]
Thank you

**Pull request closed without merging**
