### PR TITLE
Allow local file parser

### PR DESCRIPTION
**Pull request by ehooo**
if local_file_path is file it will loaded locally.
Useful if not internet connection is available

### CODE REVIEW

**Comment by ehooo** [comment]
Hi @joshswimlane , i'm not sure if you this is better idea create a subclass that allows local file parsing.
Please let me know and i will happy to change it.

**Comment by joshswimlane** [comment]
I think it should be added as a subclass which will support (in the future) additional data points. It makes sense to subclass it now. Thanks!

**Comment by ehooo** [comment]
I'll do.

**Comment by joshswimlane** [comment]
Adding a configuration layer that handles this.  Thanks for the support but closing this out as it is stale now.

**Pull request closed without merging**
