### PR TITLE
3.0.2 Release

### PR DESCRIPTION
**Pull request by MSAdministrator**
- Updated Documentation
- Removed version

### CODE REVIEW

**Comment by MSAdministrator** [comment]
Closes #57 #55

**Comment by doomedraven** [comment]
Hello, there is also one extra issue, the config file even the path is specified, it will be writen to `$HOME/pyattch/config.yml`

```
>>> import os
>>> from lib.cuckoo.common.constants import CUCKOO_ROOT
>>> from pyattck import Attck
>>> mitre = Attck(
...                 data_path=os.path.join(CUCKOO_ROOT, "data", "mitre"),
...                 config_file_path=os.path.join(CUCKOO_ROOT, "data", "mitre", "config.yml"),
...             )
config_file_path /opt/CAPEv2/data/mitre/config.yml # debug print before if ->  print("config_path", "config_file_path", config_file_path)
/opt/CAPEv2/data/mitre/config.yml # debug print after variable set -> print(Configuration.__CONFIG_FILE)
/opt/CAPEv2/data/mitre /opt/CAPEv2/data/mitre
>>> import os
>>> os.listdir("/opt/CAPEv2/data/mitre/")
['enterprise_attck_nist_800_53_rev4_controls.json', 'enterprise_attck.json', 'mobile_attck.json', 'preattack.json', 'enterprise_attck_dataset.json', 'enterprise_attck_nist_data.json']

```

```
        self.__nested_subtechniques = nested_subtechniques
        print("config_path", "config_file_path", config_file_path)
        if config_file_path:
            Configuration.__CONFIG_FILE = config_file_path
        print(Configuration.__CONFIG_FILE)
        Configuration().set(data_path=data_path)
        self.__datasets = AttckDatasets()
```

**Comment by doomedraven** [comment]
and if you move config but not removing folder, it will fail if you rerun initialization

```
>>> mitre = Attck(
...                 data_path=os.path.join(CUCKOO_ROOT, "data", "mitre"),
...                 config_file_path=os.path.join(CUCKOO_ROOT, "data", "mitre", "config.yml"),
...             )
config_path config_file_path /opt/CAPEv2/data/mitre/config.yml
/opt/CAPEv2/data/mitre/config.yml
/opt/CAPEv2/data/mitre /opt/CAPEv2/data/mitre
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cape/.local/lib/python3.8/site-packages/pyattck/attck.py", line 214, in __init__
    Configuration().set(data_path=data_path)
  File "/home/cape/.local/lib/python3.8/site-packages/pyattck/configuration.py", line 83, in set
    self.__write_config(self.__DATASETS_MAP)
  File "/home/cape/.local/lib/python3.8/site-packages/pyattck/configuration.py", line 89, in __write_config
    os.makedirs(os.path.dirname(self.__CONFIG_FILE))
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/cape/pyattck'
```

**Comment by doomedraven** [comment]
having version is useful for tools where your tool is integrated, just tip, as in many cases you don't have a way to control which version of lib user has installed

**Comment by MSAdministrator** [comment]
@doomedraven im not following  - pyattck is versioned

**Comment by doomedraven** [comment]
i mean to ensure that my users of my tool having the proper version of pyattck, i could check as X, but you have removed version number no?

````
from pyattck import version
if version != X:
   print("install proper version of pyattck")
```
https://github.com/swimlane/pyattck/pull/58/commits/d9c94a42f78c588d514d473be0063d1278d88c69

**Comment by MSAdministrator** [comment]
@doomedraven Ah, I see what you mean - yes its removed from importing it that way if you do this you should be good to go.

```
import pyattck
if pyattck.__version__ == '4.0.1':
    print("Install proper version of pyattck")
```

**Comment by doomedraven** [comment]
ah thanks for example

**Pull request closed without merging**
